openapi: 3.0.1
info:
  title: MainApi
  description: API Definition of MainApi
  version: 1.0.0
servers:
- url: http://localhost:8290/sales
paths:
  /:
    get:
      responses:
        default:
          description: Default response
