openapi: 3.0.1
info:
  title: FileIntegrationApi
  description: API Definition of FileIntegrationApi
  version: 1.0.0
servers:
- url: http://localhost:8290/fileTransport
paths:
  /:
    get:
      responses:
        default:
          description: Default response
