openapi: 3.0.1
info:
  title: KafkaPublishAPI
  description: API Definition of KafkaPublishAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/kafkaIntegration
paths:
  /:
    post:
      responses:
        default:
          description: Default response
