openapi: 3.0.1
info:
  title: LinkedInDataIntegration
  description: API Definition of LinkedInDataIntegration
  version: 1.0.0
servers:
- url: http://localhost:8290/linkedInData
paths:
  /:
    get:
      responses:
        default:
          description: Default response
