openapi: 3.0.1
info:
  title: SalesforceApi
  description: API Definition of SalesforceApi
  version: 1.0.0
servers:
- url: http://localhost:8290/main
paths:
  /:
    get:
      responses:
        default:
          description: Default response
