openapi: 3.0.1
info:
  title: XmlIntegration
  description: API Definition of XmlIntegration
  version: 1.0.0
servers:
- url: http://localhost:8290/xmlIntegration
paths:
  /:
    get:
      responses:
        default:
          description: Default response
