openapi: 3.0.1
info:
  title: ZoomInfoDataIntegration
  description: API Definition of ZoomInfoDataIntegration
  version: 1.0.0
servers:
- url: http://localhost:8290/csvIntegration
paths:
  /:
    get:
      responses:
        default:
          description: Default response
